server:
  port: 8080
spring:
  application:
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.164.128:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456789
  mail:
    username:
    password:
    host: smtp.qq.com
  redis:
    host: 192.168.164.128
    port: 6379
    password: 123456789
    database: 0 #操作0号数据库，Redis默认有16个数据库
    jedis: # redis连接池配置
      pool:
        max-active: 8 #最大连接数
        max-idle: 4 # 连接池中最大空闲连接
        max-wait: 1ms # 连接池中对打阻塞时间
        min-idle: 0 #连接池中最小空闲连接

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\Image\
